AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions용 IAM 역할 생성 (기존 OIDC Provider 사용)'

Parameters:
  GitHubOrg:
    Type: String
    Default: 'two2gether'
    Description: 'GitHub 조직 이름 또는 사용자명'
  
  GitHubRepo:
    Type: String
    Default: 'where-we-go'
    Description: 'GitHub 저장소 이름'
    
  ProjectName:
    Type: String
    Default: 'wherewego'
    Description: '프로젝트 이름'

  OIDCProviderArn:
    Type: String
    Default: 'arn:aws:iam::ACCOUNT_ID:oidc-provider/token.actions.githubusercontent.com'
    Description: '기존 GitHub OIDC Provider ARN (ACCOUNT_ID를 실제 계정 ID로 변경)'

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-github-actions-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${GitHubRepo}:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Policies:
        - PolicyName: GitHubActionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                  - 'secretsmanager:GetSecretValue'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: 'GitHub Actions Deployment'

Outputs:
  GitHubActionsRoleArn:
    Description: 'GitHub Actions용 IAM 역할 ARN'
    Value: !GetAtt GitHubActionsRole.Arn